export const TRANSLATIONS = [
  { id: "KJV", name: "King James Version", abbreviation: "KJV" },
  { id: "NIV", name: "New International Version", abbreviation: "NIV" },
  { id: "ESV", name: "English Standard Version", abbreviation: "ESV" },
  { id: "NKJV", name: "New King James Version", abbreviation: "NKJV" },
];

export const SEARCH_MODES = {
  EXACT: "Reference",
  FUZZY: "Quote",
  SEMANTIC: "Theme",
  VOICE: "voice",
};

export const BOOKS_OT = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1 Samuel",
  "2 Samuel",
  "1 Kings",
  "2 Kings",
  "1 Chronicles",
  "2 Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "Song of Solomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
];

export const BOOKS_NT = [
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "2 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1 Peter",
  "2 Peter",
  "1 John",
  "2 John",
  "3 John",
  "Jude",
  "Revelation",
];

export const ALL_BOOKS = [...BOOKS_OT, ...BOOKS_NT];

export const SOUND_MODE_TRIGGER_WORDS = ["search", "find", "show", "look up", "read", "quote"];
