/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectionRouteImport } from './routes/projection'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const ProjectionRoute = ProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/operator': typeof OperatorRoute
  '/project': typeof ProjectRoute
  '/projection': typeof ProjectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/operator': typeof OperatorRoute
  '/project': typeof ProjectRoute
  '/projection': typeof ProjectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/operator': typeof OperatorRoute
  '/project': typeof ProjectRoute
  '/projection': typeof ProjectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/app'
    | '/auth'
    | '/operator'
    | '/project'
    | '/projection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/app'
    | '/auth'
    | '/operator'
    | '/project'
    | '/projection'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/app'
    | '/auth'
    | '/operator'
    | '/project'
    | '/projection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  OperatorRoute: typeof OperatorRoute
  ProjectRoute: typeof ProjectRoute
  ProjectionRoute: typeof ProjectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projection': {
      id: '/projection'
      path: '/projection'
      fullPath: '/projection'
      preLoaderRoute: typeof ProjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  OperatorRoute: OperatorRoute,
  ProjectRoute: ProjectRoute,
  ProjectionRoute: ProjectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
